version: 2
builds:
  - id: rust
    builder: rust
    dir: rust
    binary: popcorn-cli
    command: build
    targets:
      - x86_64-unknown-linux-gnu
      - x86_64-apple-darwin
      - x86_64-pc-windows-gnu
      - aarch64-unknown-linux-gnu
