#!POPCORN leaderboard grayscale
#!POPCORN gpu A100

"""
Popcorn submission template generated by `popcorn setup`.

README-aligned notes:
- Submissions are a single Python file.
- You can install extra dependencies at runtime with `pip` if needed.
- Submit with: `popcorn submit submission.py`
"""


def solution():
    # Replace with your kernel implementation.
    return "hello from popcorn"


if __name__ == "__main__":
    print(solution())
